{
    "comments": [
        {
            "author": null,
            "body": "Thanks for the report.\n\nI have added the extra syncs required to fix this to SVN and the fix will be\nincluded in 5.5.21 onwards.",
            "date": "20061111T16:19:20",
            "id": 0
        }
    ],
    "component": "Catalina",
    "description": "JDBCRealm.getPassword throws NullPointerException\n\nI'm using tomcat 5.5.20 with postgresql-8.1-407.jdbc3.jar and postgresql-8.1.4\non Ubuntu Dapper. Authenticating two users simultaneously with HTTP DIGEST\ncauses sometimes the following errors and a 401 Unauthorized reply:\n\n30.10.2006 14:24:54 org.apache.catalina.realm.JDBCRealm getPassword\nSEVERE: Exception performing authentication\norg.postgresql.util.PSQLException: ERROR: invalid message format\n        at\norg.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:1525)\n        at\norg.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1309)\n        at\norg.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:188)\n        at\norg.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:452)\n        at\norg.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:354)\n        at\norg.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:258)\n        at org.apache.catalina.realm.JDBCRealm.getPassword(JDBCRealm.java:546)\n        at org.apache.catalina.realm.RealmBase.getDigest(RealmBase.java:1156)\n        at org.apache.catalina.realm.RealmBase.authenticate(RealmBase.java:365)\n        at\norg.apache.catalina.authenticator.DigestAuthenticator.findPrincipal(DigestAuthenticator.java:282)\n        at\norg.apache.catalina.authenticator.DigestAuthenticator.authenticate(DigestAuthenticator.java:175)\n        at\norg.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)\n        at\norg.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:126)\n        at\norg.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:105)\n        at\norg.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:107)\n        at\norg.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:148)\n        at\norg.apache.coyote.http11.Http11Processor.process(Http11Processor.java:869)\n        at\norg.apache.coyote.http11.Http11BaseProtocol$Http11ConnectionHandler.processConnection(Http11BaseProtocol.java:664)\n        at\norg.apache.tomcat.util.net.PoolTcpEndpoint.processSocket(PoolTcpEndpoint.java:527)\n        at\norg.apache.tomcat.util.net.LeaderFollowerWorkerThread.runIt(LeaderFollowerWorkerThread.java:80)\n        at\norg.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:684)\n        at java.lang.Thread.run(Thread.java:595)\n30.10.2006 14:24:54 org.apache.catalina.connector.CoyoteAdapter service\nSEVERE: An exception or error occurred in the container during the request\nprocessing\njava.lang.NullPointerException\n        at org.apache.catalina.realm.JDBCRealm.getPassword(JDBCRealm.java:568)\n        at org.apache.catalina.realm.JDBCRealm.getPrincipal(JDBCRealm.java:594)\n        at org.apache.catalina.realm.RealmBase.authenticate(RealmBase.java:398)\n        at\norg.apache.catalina.authenticator.DigestAuthenticator.findPrincipal(DigestAuthenticator.java:282)\n        at\norg.apache.catalina.authenticator.DigestAuthenticator.authenticate(DigestAuthenticator.java:175)\n        at\norg.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)\n        at\norg.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:126)\n        at\norg.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:105)\n        at\norg.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:107)\n        at\norg.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:148)\n        at\norg.apache.coyote.http11.Http11Processor.process(Http11Processor.java:869)\n        at\norg.apache.coyote.http11.Http11BaseProtocol$Http11ConnectionHandler.processConnection(Http11BaseProtocol.java:664)\n        at\norg.apache.tomcat.util.net.PoolTcpEndpoint.processSocket(PoolTcpEndpoint.java:527)\n        at\norg.apache.tomcat.util.net.LeaderFollowerWorkerThread.runIt(LeaderFollowerWorkerThread.java:80)\n        at\norg.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:684)\n        at java.lang.Thread.run(Thread.java:595)",
    "hasPatch": false,
    "hasScreenshot": false,
    "id": "40844",
    "issuetypeClassified": "BUG",
    "issuetypeTracker": "BUG",
    "priority": "P2 normal",
    "product": "Tomcat 5",
    "project": "TOMCAT",
    "summary": "JDBCRealm.getPassword throws NullPointerException",
    "systemSpecification": true,
    "version": "5.5.20"
}