{
    "comments": [
        {
            "author": null,
            "body": "Created attachment 24825\nPatch to fix NPE",
            "date": "20100111T05:46:00",
            "id": 0
        },
        {
            "author": null,
            "body": "Many thanks for the patch. It has been applied to trunk and proposed for 6.0.x and 5.5.x.",
            "date": "20100112T14:46:02",
            "id": 1
        },
        {
            "author": null,
            "body": "Thanks again for the patch. It has been applied to 6.0.x and will be included in 6.0.23 onwards.",
            "date": "20100113T02:38:20",
            "id": 2
        },
        {
            "author": null,
            "body": "Applied to 5.5, will be in 5.5.29 onwards. Thank you.",
            "date": "20100303T16:51:54",
            "id": 3
        }
    ],
    "component": "Catalina",
    "description": "Created attachment 24824\nPatch to fix NPE\n\nThere is a NullPointerException being thrown when the server attempts to look up a non-existent user in JNDIRealm.\n\nSpecifically, the getUser(DirContext, String) method will return null if the user is not found.  However, getPrincipal(DirContext, String) will not check to see if the result from getUser() is null.\n\nI'm attaching a patch from the 6.0.20 tag but this should also be backported to the 5.5.x branch as well because the issue exists there.",
    "hasPatch": false,
    "hasScreenshot": false,
    "id": "48516",
    "issuetypeClassified": "BUG",
    "issuetypeTracker": "BUG",
    "priority": "P2 normal",
    "product": "Tomcat 5",
    "project": "TOMCAT",
    "summary": "NullPointerException in JNDIRealm",
    "systemSpecification": true,
    "version": "5.5.28"
}