{
    "comments": [
        {
            "author": "Michael McCandless",
            "body": "The fix is trivial: add a try/finally to mergeInit to clear the\ninternal tracking on exception.  I'll commit shortly.",
            "date": "2008-03-09T08:06:42.152+0000",
            "id": 0
        },
        {
            "author": "Michele Bini",
            "body": "Uhm, shouldn't the patch be committed in the 2.3 branch, too, as it affects 2.3.1?",
            "date": "2008-03-10T10:08:28.544+0000",
            "id": 1
        },
        {
            "author": "Michael McCandless",
            "body": "Yes, I agree.  At some point soon we should do a 2.3.2 point release, and I'll port this issue back for that.",
            "date": "2008-03-10T10:13:46.982+0000",
            "id": 2
        },
        {
            "author": "Hoss Man",
            "body": "targeted for 2.3.2 bug fix release",
            "date": "2008-03-11T19:29:54.618+0000",
            "id": 3
        }
    ],
    "component": "core/index",
    "description": "If you're using CMS (the default) and mergeInit hits an exception (eg\nOOME), we are not properly clearing IndexWriter's internal tracking of\nrunning merges.  This causes IW.close() to hang while it incorrectly\nwaits for these non-started merges to finish.\n\n",
    "hasPatch": false,
    "hasScreenshot": false,
    "id": "LUCENE-1210",
    "issuetypeClassified": "BUG",
    "issuetypeTracker": "BUG",
    "priority": "Minor",
    "product": "LUCENE",
    "project": "LUCENE",
    "summary": "IndexWriter & ConcurrentMergeScheduler deadlock case if starting a merge hits an exception",
    "systemSpecification": true,
    "version": "2.3, 2.3.1"
}