{
    "comments": [
        {
            "author": "Stefan Guggisberg",
            "body": "fixed in svn rev. 397583 \n\nthanks for reporting this issue!",
            "date": "2006-04-27T23:23:22.000+0000",
            "id": 0
        },
        {
            "author": "Jukka Zitting",
            "body": "Merged for 1.0.1 in revision 409597.",
            "date": "2006-05-26T16:03:10.000+0000",
            "id": 1
        }
    ],
    "component": "jackrabbit-core",
    "description": "Binding a repository to a nameserver using RegistryHelper causes the next subsequent lookup to fail.  This is what I observerd:\n\n1. RegistryHelper.registerRepository creates a new BindableRepository and initializes it.  This, in turn, initializes the \"real\" repository (i.e. delagtee).  It then binds this reference with the nameserver.\n\n2. On the next lookup, BindableRepositoryFactory.getObjectInstance is invoked.  Thie method checks it's cache for a repository.  Since one does not exist yet, it creates a new BindableRepository and tries to initialize it.  This fails since the call to RegistryHelper.registerRepository already initialized the repository.\n\nThe error message basically says the repository is already in use by another process because the .lock file is present.  To fix this, I modified RegistryHelper.registerRepository to NOT initialize the repository and simply bind the \"Reference\".",
    "hasPatch": false,
    "hasScreenshot": false,
    "id": "JCR-411",
    "issuetypeClassified": "BUG",
    "issuetypeTracker": "BUG",
    "priority": "Major",
    "product": "JACKRABBIT",
    "project": "JACKRABBIT",
    "summary": "Binding repository to a nameserver with RegistryHelper causes failure on lookup.",
    "systemSpecification": true,
    "version": "1.0"
}