{
    "comments": [
        {
            "author": "hannesw@gmail.com",
            "body": "The NullPointerException actually seems to result from passing null for sourceName, the third argument to Context.evaluateString(). We either should throw a NullPointerException right away, or use some dummy source name such as \"<anonymous>\".\n\nYou also should pass a scope object as first argument to evaluateString(), otherwise you're goint to get strange errors (again, we really need some argument checking here...). The easiest way to create a standard scope object is to use Context.initStandardObjects(). \n\nSee http://www.mozilla.org/rhino/tutorial.html for more on embedding Rhino.",
            "date": "20071220T19:09:19",
            "id": 0
        },
        {
            "author": "szegedia@freemail.hu",
            "body": "Fixed by internally assigning name \"unnamed script\" when null is passed as the script name.\n\n    Checking in src/org/mozilla/javascript/Context.java;\n    /cvsroot/mozilla/js/rhino/src/org/mozilla/javascript/Context.java,v  <--  Context.java\n    new revision: 1.266; previous revision: 1.265\n\n",
            "date": "20080208T19:16:50",
            "id": 1
        }
    ],
    "component": "Compiler",
    "description": "User-Agent:       Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1)\nBuild Identifier: js 1.5(7)\n\nHere is some java code I wrote to test Rhino. I want to be able to throw an IllgalArgumentException from the javascript, but I found that I could not even execute a basic throw statement.\n\nContext ctx = Context.enter();\nctx.evaluateString(null, \"throw '42'\", null, 0, null);\nContext.exit();\n\nThe variations of the throw statement I have tried are:\nthrow ('e')\nthrow new java.lang.IllegalArgumentException()\nthrow new Packages.java.lang.IllegalArgumentException()\nthrow '42'\n\nAll of the above gives me a NullPointerException.\n\njava.lang.NullPointerException\n\tat org.mozilla.classfile.ClassFileWriter.addPush(ClassFileWriter.java:894)\n\tat org.mozilla.javascript.optimizer.BodyCodegen.generateStatement(Codegen.java:1628)\n\tat org.mozilla.javascript.optimizer.BodyCodegen.generateStatement(Codegen.java:1556)\n\tat org.mozilla.javascript.optimizer.BodyCodegen.generateBodyCode(Codegen.java:1222)\n\tat org.mozilla.javascript.optimizer.Codegen.generateCode(Codegen.java:288)\n\tat org.mozilla.javascript.optimizer.Codegen.compileToClassFile(Codegen.java:161)\n\tat org.mozilla.javascript.optimizer.Codegen.compile(Codegen.java:71)\n\tat org.mozilla.javascript.Context.compileImpl(Context.java:2343)\n\tat org.mozilla.javascript.Context.compileString(Context.java:1348)\n\tat org.mozilla.javascript.Context.compileString(Context.java:1337)\n\tat org.mozilla.javascript.Context.evaluateString(Context.java:1193)\n\tat com.istnet.script.ScriptingTest.testScriptException(ScriptingTest.java:202)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)\n\tat java.lang.reflect.Method.invoke(Method.java:585)\n\tat junit.framework.TestCase.runTest(TestCase.java:164)\n\tat junit.framework.TestCase.runBare(TestCase.java:130)\n\tat junit.framework.TestResult$1.protect(TestResult.java:110)\n\tat junit.framework.TestResult.runProtected(TestResult.java:128)\n\tat junit.framework.TestResult.run(TestResult.java:113)\n\tat junit.framework.TestCase.run(TestCase.java:120)\n\tat junit.framework.TestSuite.runTest(TestSuite.java:228)\n\tat junit.framework.TestSuite.run(TestSuite.java:223)\n\tat org.junit.internal.runners.OldTestClassRunner.run(OldTestClassRunner.java:35)\n\tat org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:38)\n\tat org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)\n\tat org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)\n\tat org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)\n\tat org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)\n\tat org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)\n\n\n\n\nReproducible: Always\n\nSteps to Reproduce:\n1. Code attached.\n2.\n3.\nActual Results:  \njava.lang.NullPointerException\n\tat org.mozilla.classfile.ClassFileWriter.addPush(ClassFileWriter.java:894)\n\tat org.mozilla.javascript.optimizer.BodyCodegen.generateStatement(Codegen.java:1628)\n\tat org.mozilla.javascript.optimizer.BodyCodegen.generateStatement(Codegen.java:1556)\n\tat org.mozilla.javascript.optimizer.BodyCodegen.generateBodyCode(Codegen.java:1222)\n\tat org.mozilla.javascript.optimizer.Codegen.generateCode(Codegen.java:288)\n\tat org.mozilla.javascript.optimizer.Codegen.compileToClassFile(Codegen.java:161)\n\tat org.mozilla.javascript.optimizer.Codegen.compile(Codegen.java:71)\n\tat org.mozilla.javascript.Context.compileImpl(Context.java:2343)\n\tat org.mozilla.javascript.Context.compileString(Context.java:1348)\n\tat org.mozilla.javascript.Context.compileString(Context.java:1337)\n\tat org.mozilla.javascript.Context.evaluateString(Context.java:1193)\n\tat com.istnet.script.ScriptingTest.testScriptException(ScriptingTest.java:202)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)\n\tat java.lang.reflect.Method.invoke(Method.java:585)\n\tat junit.framework.TestCase.runTest(TestCase.java:164)\n\tat junit.framework.TestCase.runBare(TestCase.java:130)\n\tat junit.framework.TestResult$1.protect(TestResult.java:110)\n\tat junit.framework.TestResult.runProtected(TestResult.java:128)\n\tat junit.framework.TestResult.run(TestResult.java:113)\n\tat junit.framework.TestCase.run(TestCase.java:120)\n\tat junit.framework.TestSuite.runTest(TestSuite.java:228)\n\tat junit.framework.TestSuite.run(TestSuite.java:223)\n\tat org.junit.internal.runners.OldTestClassRunner.run(OldTestClassRunner.java:35)\n\tat org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:38)\n\tat org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)\n\tat org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)\n\tat org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)\n\tat org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)\n\tat org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)\n\n\n\nExpected Results:  \nI'd like the code to throw some kind of exception in the JVM space.",
    "hasPatch": false,
    "hasScreenshot": false,
    "id": "405558",
    "issuetypeClassified": "IMPROVEMENT",
    "issuetypeTracker": "BUG",
    "priority": "-- minor",
    "product": "Rhino",
    "project": "RHINO",
    "summary": "The throw statement does not seem to behave properly.",
    "systemSpecification": true,
    "version": "other"
}