{
    "comments": [
        {
            "author": "norrisboyd@gmail.com",
            "body": "Fixed:\n\nChecking in Codegen.java;\n/cvsroot/mozilla/js/rhino/src/org/mozilla/javascript/optimizer/Codegen.java,v  <\n--  Codegen.java\nnew revision: 1.44; previous revision: 1.43\ndone",
            "date": "20010517T19:04:50",
            "id": 0
        },
        {
            "author": "pschwartau@meer.net",
            "body": "Verified on WinNT: \n                                                                                   \nhliu@allegis.com's testcase now succeeds without error -",
            "date": "20010517T20:47:52",
            "id": 1
        }
    ],
    "component": "Core",
    "description": "// --test.js\nfunction foo()\n{\n\ttry {\n\t\tvar x = bar(1, 3);\n\t\tjava.lang.System.out.println(x);\n\t} \n\tcatch (e) {}\n\n\tfunction bar(a, b) {\n\t\treturn a+b;\n\t}\n}\nfoo();\n//---\n\n1. Compile the script using \"java org.mozilla.javascript.tools.jsc.Main test.js\"\n2. Run the class file using \"java test\"\nOBSERVE: \njava.lang.VerifyError: (class: test$foo, method: call signature: \n(Lorg/mozilla/javascript/Context;Lorg/mozilla/javascript/Scriptable;Lorg/mozilla\n/javascript/Scriptable;[Ljava/lang/Object;)Ljava/lang/Object;) Inconsistent \nstack height 0 != 1\n\tat test.initScript(Unknown Source)\n\tat test.exec(Unknown Source)\n\tat org.mozilla.javascript.ScriptRuntime.main(ScriptRuntime.java, \nCompiled Code)\n\tat test.main(Unknown Source)\nException in thread \"main\"\n\nNOTE: If I remove the try/catch statement or move inner function bar() outside \nfoo(), it works.",
    "hasPatch": false,
    "hasScreenshot": false,
    "id": "80322",
    "issuetypeClassified": "BUG",
    "issuetypeTracker": "BUG",
    "priority": "-- normal",
    "product": "Rhino",
    "project": "RHINO",
    "summary": "Rhino: failed to execute the script that has inner function",
    "systemSpecification": true,
    "version": "other"
}